jobs:
  - job: Plan_${{ parameters.environment }}_${{ parameters.component }}
    pool:
      vmImage: ${{ parameters.agentPool }}
    steps:
      - task: TerraformInstaller@0
        inputs:
          terraformVersion: ${{ parameters.terraformVersion }}
      - task: TerraformCLI@0
        displayName: Init - launchdarkly
        inputs:
          command: 'init'
          commandOptions: '-lock=false' # don't lock on PRs / validate phase
          backendType: 'azurerm'
          backendServiceArm: 'Reform-CFT-Mgmt'
          backendAzureRmResourceGroupName: 'reform-cft-mgmt'
          backendAzureRmStorageAccountName: 'reformcftmgmt'
          backendAzureRmContainerName: 'tfstate'
          backendAzureRmKey: 'launchdarkly/launchdarkly.tfstate'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
      - task: TerraformCLI@0
        displayName: Plan - launchdarkly
        inputs:
          command: 'plan'
          commandOptions: '-out=launchdarkly-plan'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          environmentServiceName: 'Reform-CFT-Mgmt'
      - task: Bash@3
        displayName: "Remove local tfstate"
        inputs:
          targetType: 'inline'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          script: |
            rm -f terraform.tfstate* && rm -rf .terraform/
      - publish: $(System.DefaultWorkingDirectory)/launchdarkly-plan
        artifact: launchdarkly-plan