jobs:
  - deployment: Deploy
    pool:
      vmImage: ${{ parameters.agentPool }}
    environment: mgmt
    strategy:
      # default deployment strategy
      runOnce:
        deploy:
          steps:
            - checkout: cnp-azuredevops-libraries
              displayName: Checkout cnp-azuredevops-libraries
              clean: true
              persistCredentials: false
              path: cnp-azuredevops-libraries
            - download: current
              displayName: 'Download artifacts'
              artifact: drop
            - download: current
              displayName: 'Download tfplan launchdarkly'
              artifact: launchdarkly${{ parameters.build }}plan
            - task: CopyFiles@2
              inputs:
                sourceFolder: '$(Pipeline.Workspace)/launchdarkly${{ parameters.build }}plan'
                targetFolder: '$(Pipeline.Workspace)/drop'
            - task: Bash@3
              displayName: Terraform install (tfenv)
              inputs:
                filePath: $(Pipeline.Workspace)/cnp-azuredevops-libraries/scripts/tfenv-install-terraform.sh
            - task: TerraformCLI@0
              displayName: Init - launchdarkly
              inputs:
                command: 'init'
                backendType: 'azurerm'
                backendServiceArm: 'DTS-CFTPTL-INTSVC'
                backendAzureRmResourceGroupName: 'core-infra-intsvc-rg'
                backendAzureRmStorageAccountName: 'cftptlintsvc'
                backendAzureRmContainerName: 'tfstate'
                backendAzureRmKey: 'launchdarkly.tfstate'
                workingDirectory: '$(Pipeline.Workspace)/drop'
            - task: TerraformCLI@0
              displayName: Apply - launchdarkly
              inputs:
                command: 'apply'
                commandOptions: 'launchdarkly${{ parameters.build }}plan'
                environmentServiceName: 'DTS-CFTPTL-INTSVC'
                workingDirectory: '$(Pipeline.Workspace)/drop'
