name: offboard-launchdarkly-user

pr:
  paths:
    include:
      - azure-pipelines-launchdarkly-offboard.yml

schedules:
- cron: "0 12 * * 0"
  displayName:  Weekly Sunday 
  branches:
    include:
    - main
  always: true

variables:
  timeoutInMinutes: 60
  agentPool: 'ubuntu-18.04'
  
stages:
  - stage: launchdarkly-offboard-users
    jobs:
      - job: launchdarkly
        timeoutInMinutes: ${{ variables.timeoutInMinutes }}
        pool:
          vmImage: ${{ variables.agentPool }}
        steps:
        - task: AzureKeyVault@1
          displayName: 'Get API token'
          inputs:
            runAsPreJob: false
            ConnectedServiceName: 'DTS-CFTPTL-INTSVC'
            keyVaultName: 'cftptl-intsvc'
            secretsFilter: 'launchdarkly-access-token'
        - task: Bash@3
          displayName: 'Remove user from launchdarkly'
          inputs:
            filePath: pipeline-scripts/launchdarkly-offboard.sh
          env:
            TOKEN: $(launchdarkly-access-token)