# Docs:
# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - master
    
variables:
  terraformVersion: 0.12.20
  agentPool: 'ubuntu-18.04'

stages:
  - stage: GetArtifacts
    jobs:
      - job: Validate
        pool:
          vmImage: ${{ variables.agentPool }}
        steps:
          - template: pipeline-templates/terraform-plan.yaml
            parameters:
              build: $(Build.BuildNumber)  
              agentPool: ${{ variables.agentPool }}
              terraformVersion: ${{ variables.terraformVersion }}

  
  - stage: ApplyLaunchdarkly
    dependsOn: GetArtifacts
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    jobs: 
      - template: pipeline-templates/terraform-apply.yaml
        parameters:
          build: $(Build.BuildNumber)
          agentPool: ${{ variables.agentPool }}
          terraformVersion: ${{ variables.terraformVersion }}